spring:
  datasource:
    url: jdbc:h2:mem:demo
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: db/root-changelog.xml
  h2:
    console:
      enabled: true